### ISSUE TITLE
apigee-opdk-restart doesn't exist

### ISSUE THREAD

**Issue by Woulei** [apigee/ansible-opdk-accelerator#1]
In the requirements for restart-planet in the post-installation folder is a reference to the apigee-opdk-restart git repository. However, this doesn't exist.

Can we skip this installtion or is it moved? How to fix?

**Comment by carlosfrias** [comment]
I updated the requirements and playbook so that the correct roles are downloaded and used. My local tests show it working please let me know if you have additional issues.
